name: Deployment

on:
  push:
    branches: [master, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - uses: actions/setup-go@v3.3.1
        with:
          go-version: 1.18
          cache: true
      - run: go get .

      - name: Test Integration
        run: make test-integration

      - name: Test Benchmark
        run: make test-benchmark

      - name: Test Unit
        run: make test-unit

#  deploy-service:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      # Check-out your repository.
#      - name: Checkout
#        uses: actions/checkout@v3.1.0
#
#      - name: Deploy
#        uses: gonuit/heroku-docker-deploy@v1.3.3
#        with:
#          email: ${{ secrets.HEROKU_EMAIL }}
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
#          docker_options: "--no-cache"
#
#  deploy-consumer-service:
#    runs-on: ubuntu-latest
#    needs: test
#    steps:
#      # Check-out your repository.
#      - name: Checkout
#        uses: actions/checkout@v3.1.0
#
#      - name: Deploy
#        uses: gonuit/heroku-docker-deploy@v1.3.3
#        with:
#          email: ${{ secrets.HEROKU_EMAIL }}
#          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
#          heroku_app_name: ${{ secrets.HEROKU_MQ_CONSUMER_SERVICE_NAME }}
#          docker_options: "--no-cache"
#          dockerfile_name: "consumer.Dockerfile"
#          process_type: worker
